// Package sarif parses a bounded subset of SARIF 2.1.0 into deterministic
// source records. It does not normalize observations or infer scan coverage.
package sarif

import (
	"errors"
	"fmt"
)

const (
	// Format identifies the supported source format.
	Format = "sarif"
	// FormatVersion is the only SARIF version accepted by this parser version.
	FormatVersion = "2.1.0"
	// ParserVersion changes whenever identical source bytes may produce a
	// meaningfully different parsed representation.
	ParserVersion = "1"
)

// Limits bounds parser resource use and output cardinality. Every field is
// required so callers cannot accidentally enable an unbounded parser.
type Limits struct {
	MaxBytes                       int64
	MaxJSONDepth                   int
	MaxObjectMembers               int
	MaxArrayElements               int
	MaxStringBytes                 int
	MaxRuns                        int
	MaxRulesPerRun                 int
	MaxResultsPerRun               int
	MaxInvocationsPerRun           int
	MaxLocationsPerResult          int
	MaxFingerprintsPerResult       int
	MaxWarnings                    int
	MaxUnsupportedFieldsPerWarning int
}

// DefaultLimits returns conservative finite limits for a server-side parser.
// Deployments may choose smaller values; New rejects zero and extreme values.
func DefaultLimits() Limits {
	return Limits{
		MaxBytes:                       100 << 20,
		MaxJSONDepth:                   64,
		MaxObjectMembers:               100_000,
		MaxArrayElements:               100_000,
		MaxStringBytes:                 1 << 20,
		MaxRuns:                        1_000,
		MaxRulesPerRun:                 100_000,
		MaxResultsPerRun:               100_000,
		MaxInvocationsPerRun:           1_000,
		MaxLocationsPerResult:          1_000,
		MaxFingerprintsPerResult:       1_000,
		MaxWarnings:                    1_000,
		MaxUnsupportedFieldsPerWarning: 64,
	}
}

// ErrorCode is a stable, safe parser failure classification. It never embeds
// scanner-controlled report content.
type ErrorCode string

const (
	ErrorInvalidConfiguration ErrorCode = "invalid_configuration"
	ErrorInputRead            ErrorCode = "input_read_failed"
	ErrorInputTooLarge        ErrorCode = "input_too_large"
	ErrorInvalidEncoding      ErrorCode = "invalid_utf8"
	ErrorMalformedJSON        ErrorCode = "malformed_json"
	ErrorUnsupportedVersion   ErrorCode = "unsupported_version"
	ErrorInvalidSARIF         ErrorCode = "invalid_sarif"
	ErrorLimitExceeded        ErrorCode = "limit_exceeded"
	ErrorCancelled            ErrorCode = "cancelled"
)

// ParseError distinguishes parser failures from scanner-reported outcomes.
// Path is generated by the parser and contains no scanner-controlled values.
type ParseError struct {
	code ErrorCode
	path string
}

func (parseError *ParseError) Error() string {
	if parseError.path == "" {
		return fmt.Sprintf("sarif parser: %s", parseError.code)
	}
	return fmt.Sprintf("sarif parser: %s at %s", parseError.code, parseError.path)
}

// Code returns the stable machine-readable classification.
func (parseError *ParseError) Code() ErrorCode { return parseError.code }

// Path returns a parser-generated JSON pointer to the rejected structure.
func (parseError *ParseError) Path() string { return parseError.path }

// ErrorCodeOf extracts a parser error code without exposing implementation or
// report details.
func ErrorCodeOf(err error) (ErrorCode, bool) {
	var parseError *ParseError
	if !errors.As(err, &parseError) {
		return "", false
	}
	return parseError.code, true
}

type ParserIdentity struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// Document is a source-preserving parser result. Raw report bytes remain the
// evidence of record; SourcePointer fields locate each derived record in them.
type Document struct {
	Format            string         `json:"format"`
	FormatVersion     string         `json:"format_version"`
	SchemaURI         string         `json:"schema_uri,omitempty"`
	Parser            ParserIdentity `json:"parser"`
	Runs              []Run          `json:"runs"`
	Warnings          []Warning      `json:"warnings,omitempty"`
	WarningsTruncated bool           `json:"warnings_truncated,omitempty"`
}

type Run struct {
	Index             int                `json:"index"`
	SourcePointer     string             `json:"source_pointer"`
	Tool              Tool               `json:"tool"`
	AutomationDetails *AutomationDetails `json:"automation_details,omitempty"`
	Invocations       []Invocation       `json:"invocations,omitempty"`
	Rules             []Rule             `json:"rules,omitempty"`
	Results           []Result           `json:"results,omitempty"`
}

type Tool struct {
	Name            string `json:"name"`
	FullName        string `json:"full_name,omitempty"`
	Version         string `json:"version,omitempty"`
	SemanticVersion string `json:"semantic_version,omitempty"`
	InformationURI  string `json:"information_uri,omitempty"`
}

type AutomationDetails struct {
	ID              string `json:"id,omitempty"`
	GUID            string `json:"guid,omitempty"`
	CorrelationGUID string `json:"correlation_guid,omitempty"`
}

type Invocation struct {
	Index               int    `json:"index"`
	SourcePointer       string `json:"source_pointer"`
	ExecutionSuccessful bool   `json:"execution_successful"`
	StartTimeUTC        string `json:"start_time_utc,omitempty"`
	EndTimeUTC          string `json:"end_time_utc,omitempty"`
	ExitCode            *int   `json:"exit_code,omitempty"`
	ExitCodeDescription string `json:"exit_code_description,omitempty"`
	StartFailureMessage string `json:"process_start_failure_message,omitempty"`
}

type Rule struct {
	Index            int      `json:"index"`
	SourcePointer    string   `json:"source_pointer"`
	ID               string   `json:"id"`
	Name             string   `json:"name,omitempty"`
	ShortDescription *Message `json:"short_description,omitempty"`
	FullDescription  *Message `json:"full_description,omitempty"`
	Help             *Message `json:"help,omitempty"`
	DefaultLevel     string   `json:"default_level,omitempty"`
}

type Result struct {
	Index               int          `json:"index"`
	SourcePointer       string       `json:"source_pointer"`
	GUID                string       `json:"guid,omitempty"`
	CorrelationGUID     string       `json:"correlation_guid,omitempty"`
	RuleID              string       `json:"rule_id,omitempty"`
	RuleIndex           *int         `json:"rule_index,omitempty"`
	Level               string       `json:"level,omitempty"`
	Kind                string       `json:"kind,omitempty"`
	BaselineState       string       `json:"baseline_state,omitempty"`
	Message             Message      `json:"message"`
	Locations           []Location   `json:"locations,omitempty"`
	Fingerprints        []NamedValue `json:"fingerprints,omitempty"`
	PartialFingerprints []NamedValue `json:"partial_fingerprints,omitempty"`
}

type Message struct {
	ID        string   `json:"id,omitempty"`
	Text      string   `json:"text,omitempty"`
	Markdown  string   `json:"markdown,omitempty"`
	Arguments []string `json:"arguments,omitempty"`
}

type Location struct {
	Index         int     `json:"index"`
	SourcePointer string  `json:"source_pointer"`
	URI           string  `json:"uri,omitempty"`
	URIBaseID     string  `json:"uri_base_id,omitempty"`
	ArtifactIndex *int    `json:"artifact_index,omitempty"`
	Region        *Region `json:"region,omitempty"`
}

type Region struct {
	StartLine   *int `json:"start_line,omitempty"`
	StartColumn *int `json:"start_column,omitempty"`
	EndLine     *int `json:"end_line,omitempty"`
	EndColumn   *int `json:"end_column,omitempty"`
}

type NamedValue struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type WarningCode string

const WarningUnsupportedFields WarningCode = "unsupported_fields"

// Warning records supported source data that this parser version did not map.
// The raw artifact and Path remain authoritative for the omitted values.
type Warning struct {
	Code            WarningCode `json:"code"`
	Path            string      `json:"path"`
	FieldCount      int         `json:"field_count"`
	Fields          []string    `json:"fields,omitempty"`
	FieldsTruncated bool        `json:"fields_truncated,omitempty"`
}
